package com.login.authserver.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "user")
public class AuthUser {
	private String email;
	private String password;
//	ID is auto-generated by the DB - no setter
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer id;

	public AuthUser() {}
	
	public AuthUser(String email, String password) {
		this.email = email;
		this.password = password;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
	public Integer getId() {
		return id;
	}

}
